stages:
  - build_stage_dev
  - deploy_stage_dev
  - failed_stage_dev

variables:
  IMAGE_NAME_DEV: go-sketelon:dev-$CI_PIPELINE_ID
  DOCKER_NAME: go-sketelon
  GIT_STRATEGY: clone

build_stage_dev:
  image: docker:latest
  services:
    - docker:dind
  stage: build_stage_dev
  script:
    - docker build -t $IMAGE_NAME_DEV .
  tags:
    - dev-api-group
  only:
    - dev

deploy_stage_dev:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy_stage_dev
  script:
    - docker-compose up -d
    - sh ci-notify.sh ✅ Udah+Ke+Deploy+Di+Dev+Nih
  tags:
    - dev-api-group
  only:
    - dev

failed_stage_dev:
  stage: failed_stage_dev
  script:
    - sh ci-notify.sh ❌ Gagal+deploy+nih+tolong+ceki+ceki
  when: on_failure
  tags:
    - dev-api-group